# Generated by Django 4.2 on 2023-05-09 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('image', models.ImageField(default='default-image_450.png', upload_to='Category')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(default='download.png', upload_to='Items')),
                ('quantity', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('Color', models.CharField(max_length=50)),
                ('details', models.TextField(max_length=500)),
                ('active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Sold', 'Sold'), ('Returns', 'Returns')], max_length=50)),
                ('colors', models.CharField(choices=[('Black', 'Black'), ('Grey', 'Grey'), ('White', 'White'), ('Blue', 'Blue'), ('Brown', 'Brown'), ('Red', 'Red')], max_length=50)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Item_Category', to='ErpApp.category')),
            ],
        ),
    ]
