# Generated by Django 3.2 on 2023-02-08 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('brand', models.CharField(max_length=150)),
                ('item_img', models.ImageField(blank=True, null=True, upload_to='item_images')),
                ('brand_img', models.ImageField(blank=True, null=True, upload_to='brand_images')),
                ('quantity', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Color', models.CharField(blank=True, max_length=50, null=True)),
                ('details', models.TextField(blank=True, max_length=500, null=True)),
                ('active', models.BooleanField(default=True)),
                ('status', models.CharField(blank=True, choices=[('Available', 'Available'), ('Sold', 'Sold'), ('Soon', 'Soon')], max_length=50, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Category', to='ErpApp.category')),
            ],
        ),
    ]
