# Generated by Django 4.2 on 2023-05-09 12:21

from django.db import migrations, models
import utils.generate_code


class Migration(migrations.Migration):

    dependencies = [
        ('ErpApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='Color',
        ),
        migrations.AddField(
            model_name='item',
            name='code',
            field=models.CharField(default=utils.generate_code.generate_code, max_length=50),
        ),
    ]
